name: Publish to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.7
      - name: Generate static files
        run: |
          npm ci
          npm run generate
          touch .output/public/.nojekyll
      - name: Deploy to Pages repository
        uses: tagus/git-deploy@v0.4.1
        with:
          changes: .output/public
          repository: git@github.com:GuiArcencio/guiarcencio.github.io.git
          ssh_key: ${{ secrets.REPO_DEPLOY_KEY }}
          branch: main
          name: Guilherme Arcencio
          email: guiarcencio@hotmail.com
          clean_repo: true